name: npm-publish
on:
  push:
    tags:
      - '*'
jobs:
  npm-publish:
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish eslint-config
        uses: JS-DevTools/npm-publish@v1
        with:
          package: './packages/eslint-config/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-typescript
        uses: JS-DevTools/npm-publish@v1
        with:
          package: './packages/eslint-config-typescript/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-typescript-react
        uses: JS-DevTools/npm-publish@v1
        with:
          package: './packages/eslint-config-typescript-react/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish prettier-config
        uses: JS-DevTools/npm-publish@v1
        with:
          package: './packages/prettier-config/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
