name: Publish packages to NPM

on:
  push:
    branches:
      - master

jobs:
  npm-publish:
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    name: Publish packages to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Use Node 14
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Publish commitlint-config
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: './packages/commitlint-config/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: './packages/eslint-config/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-typescript
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: './packages/eslint-config-typescript/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish eslint-config-typescript-react
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: './packages/eslint-config-typescript-react/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish prettier-config
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: './packages/prettier-config/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish tsconfig
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: './packages/tsconfig/package.json'
          token: ${{ secrets.NPM_AUTH_TOKEN }}
