name: Test Application

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.7.0
      - name: Use Node 20
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Run test command
        run: yarn test
