name: Test Application

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Use Node 14
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 14
      - name: Install dependencies with yarn
        run: yarn install --frozen-lockfile
      - name: Run test command
        run: yarn test
